# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('count', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
