# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_subreddit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([('month', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='subreddit',
            unique_together=set([('month', 'name')]),
        ),
    ]
