# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20160504_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('percentage', models.FloatField()),
                ('phrase', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ngram',
            unique_together=set([('day', 'phrase')]),
        ),
    ]
