# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_auto_20160515_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintimeseries',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subreddittimeseries',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
